#!/bin/sh
sudo -A echo "Root permission granted" &&
gnome-screensaver-command --lock &&
if [ $(lastupdate) -gt 86400 ] # One day
then
	sudo apt update &&
	sudo apt -yu upgrade &&
	sudo apt -y autoremove
fi
sudo pm-suspend
